
 groupName: "testGroup"

 threadConfigs:
       - name: "Test1"
         channel: "RT"
         listenerCount: 1
       - name: "Test2"
         channel: "RT"
         listenerCount: 6

 cacheConfig:
      master: mymaster
      sentinels: 127.0.0.1:26379
      password: foobared
      timeout: 2
      db: 0
      maxThreads: 8
