
 groupName: "testGroup"

 threadConfigs:
       - name: "Test1"
         channel: "RT"
         listenerCount: 1
       - name: "Test2"
         channel: "RT"
         listenerCount: 6

 redisConfig:
         host: "localhost"
         port: 26379
         db: 0
         password: "foobared"